//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eh {

public class eh {
  public static IViewport CreateViewport(global::System.IntPtr hWindow) {
    global::System.IntPtr cPtr = ehPINVOKE.CreateViewport(hWindow);
    IViewport ret = (cPtr == global::System.IntPtr.Zero) ? null : new IViewport(cPtr, true);
    return ret;
  }

}

}
