//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eh {

public class IMaterial : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal IMaterial(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IMaterial obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IMaterial() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          ehPINVOKE.delete_IMaterial(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void SetDiffuseColor(float r, float g, float b, float a) {
    ehPINVOKE.IMaterial_SetDiffuseColor(swigCPtr, r, g, b, a);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetAmbientColor(float r, float g, float b, float a) {
    ehPINVOKE.IMaterial_SetAmbientColor(swigCPtr, r, g, b, a);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetSpecularColor(float r, float g, float b, float a) {
    ehPINVOKE.IMaterial_SetSpecularColor(swigCPtr, r, g, b, a);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetSpecularFactor(float f) {
    ehPINVOKE.IMaterial_SetSpecularFactor(swigCPtr, f);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetEmissionColor(float r, float g, float b, float a) {
    ehPINVOKE.IMaterial_SetEmissionColor(swigCPtr, r, g, b, a);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetDiffuseTexture(string fileName) {
    ehPINVOKE.IMaterial_SetDiffuseTexture(swigCPtr, fileName);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetReflectionTexture(string fileName) {
    ehPINVOKE.IMaterial_SetReflectionTexture(swigCPtr, fileName);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetBumpTexture(string fileName) {
    ehPINVOKE.IMaterial_SetBumpTexture(swigCPtr, fileName);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void ReloadTextures() {
    ehPINVOKE.IMaterial_ReloadTextures(swigCPtr);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
