//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eh {

public class IViewport : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal IViewport(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IViewport obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IViewport() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          ehPINVOKE.delete_IViewport(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void SetDisplayRect(int x, int y, int dx, int dy) {
    ehPINVOKE.IViewport_SetDisplayRect(swigCPtr, x, y, dx, dy);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void DrawScene() {
    ehPINVOKE.IViewport_DrawScene(swigCPtr);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string GetDriverInfo() {
    string ret = ehPINVOKE.IViewport_GetDriverInfo(swigCPtr);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool IsValid() {
    bool ret = ehPINVOKE.IViewport_IsValid(swigCPtr);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual IController Control() {
    global::System.IntPtr cPtr = ehPINVOKE.IViewport_Control(swigCPtr);
    IController ret = (cPtr == global::System.IntPtr.Zero) ? null : new IController(cPtr, false);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetModeFlag(Mode flag, bool enable) {
    ehPINVOKE.IViewport_SetModeFlag(swigCPtr, (int)flag, enable);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool GetModeFlag(Mode flag) {
    bool ret = ehPINVOKE.IViewport_GetModeFlag(swigCPtr, (int)flag);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetCameraCount() {
    int ret = ehPINVOKE.IViewport_GetCameraCount(swigCPtr);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetCameraName(int num) {
    string ret = ehPINVOKE.IViewport_GetCameraName(swigCPtr, num);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetCamera(int num) {
    ehPINVOKE.IViewport_SetCamera(swigCPtr, num);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetScene(ISceneNode scene) {
    ehPINVOKE.IViewport_SetScene(swigCPtr, ISceneNode.getCPtr(scene));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
