//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eh {

public class MaterialVector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<IMaterial>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MaterialVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MaterialVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MaterialVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ehPINVOKE.delete_MaterialVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MaterialVector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (IMaterial element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public IMaterial this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(IMaterial[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(IMaterial[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, IMaterial[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<IMaterial> global::System.Collections.Generic.IEnumerable<IMaterial>.GetEnumerator() {
    return new MaterialVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new MaterialVectorEnumerator(this);
  }

  public MaterialVectorEnumerator GetEnumerator() {
    return new MaterialVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class MaterialVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<IMaterial>
  {
    private MaterialVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public MaterialVectorEnumerator(MaterialVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public IMaterial Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (IMaterial)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    ehPINVOKE.MaterialVector_Clear(swigCPtr);
  }

  public void Add(IMaterial x) {
    ehPINVOKE.MaterialVector_Add(swigCPtr, IMaterial.getCPtr(x));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = ehPINVOKE.MaterialVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = ehPINVOKE.MaterialVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    ehPINVOKE.MaterialVector_reserve(swigCPtr, n);
  }

  public MaterialVector() : this(ehPINVOKE.new_MaterialVector__SWIG_0(), true) {
  }

  public MaterialVector(MaterialVector other) : this(ehPINVOKE.new_MaterialVector__SWIG_1(MaterialVector.getCPtr(other)), true) {
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public MaterialVector(int capacity) : this(ehPINVOKE.new_MaterialVector__SWIG_2(capacity), true) {
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  private IMaterial getitemcopy(int index) {
    global::System.IntPtr cPtr = ehPINVOKE.MaterialVector_getitemcopy(swigCPtr, index);
    IMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new IMaterial(cPtr, true);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private IMaterial getitem(int index) {
    global::System.IntPtr cPtr = ehPINVOKE.MaterialVector_getitem(swigCPtr, index);
    IMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new IMaterial(cPtr, true);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, IMaterial val) {
    ehPINVOKE.MaterialVector_setitem(swigCPtr, index, IMaterial.getCPtr(val));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(MaterialVector values) {
    ehPINVOKE.MaterialVector_AddRange(swigCPtr, MaterialVector.getCPtr(values));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public MaterialVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = ehPINVOKE.MaterialVector_GetRange(swigCPtr, index, count);
    MaterialVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new MaterialVector(cPtr, true);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, IMaterial x) {
    ehPINVOKE.MaterialVector_Insert(swigCPtr, index, IMaterial.getCPtr(x));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, MaterialVector values) {
    ehPINVOKE.MaterialVector_InsertRange(swigCPtr, index, MaterialVector.getCPtr(values));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    ehPINVOKE.MaterialVector_RemoveAt(swigCPtr, index);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    ehPINVOKE.MaterialVector_RemoveRange(swigCPtr, index, count);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public static MaterialVector Repeat(IMaterial value, int count) {
    global::System.IntPtr cPtr = ehPINVOKE.MaterialVector_Repeat(IMaterial.getCPtr(value), count);
    MaterialVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new MaterialVector(cPtr, true);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    ehPINVOKE.MaterialVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    ehPINVOKE.MaterialVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, MaterialVector values) {
    ehPINVOKE.MaterialVector_SetRange(swigCPtr, index, MaterialVector.getCPtr(values));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
