//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eh {

public class Point : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Point(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Point obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Point() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ehPINVOKE.delete_Point(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int x {
    set {
      ehPINVOKE.Point_x_set(swigCPtr, value);
    } 
    get {
      int ret = ehPINVOKE.Point_x_get(swigCPtr);
      return ret;
    } 
  }

  public int y {
    set {
      ehPINVOKE.Point_y_set(swigCPtr, value);
    } 
    get {
      int ret = ehPINVOKE.Point_y_get(swigCPtr);
      return ret;
    } 
  }

  public Point(int _x, int _y) : this(ehPINVOKE.new_Point__SWIG_0(_x, _y), true) {
  }

  public Point(int _x) : this(ehPINVOKE.new_Point__SWIG_1(_x), true) {
  }

  public Point() : this(ehPINVOKE.new_Point__SWIG_2(), true) {
  }

}

}
