/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_eh_WRAP_H_
#define SWIG_eh_WRAP_H_

struct SwigDirector_Callback : public swig::Callback, public Swig::Director {

public:
    SwigDirector_Callback();
    virtual ~SwigDirector_Callback();
    virtual void Call(float value);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(float);
    void swig_connect_director(SWIG_Callback0_t callbackCall);

private:
    SWIG_Callback0_t swig_callbackCall;
    void swig_init_callbacks();
};

struct SwigDirector_IPlugIn : public swig::IPlugIn, public Swig::Director {

public:
    SwigDirector_IPlugIn();
    virtual std::wstring GetAboutString() const;
    virtual int GetFileTypeCount() const;
    virtual std::wstring GetFileType(int i);
    virtual std::wstring GetFileExtention(int i);
    virtual bool ReadFile(std::wstring aFile, void *sceneHandle, swig::Callback *callback = nullptr);

    typedef wchar_t * (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef wchar_t * (SWIGSTDCALL* SWIG_Callback2_t)(int);
    typedef wchar_t * (SWIGSTDCALL* SWIG_Callback3_t)(int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback4_t)(void *, void *, void *);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackGetAboutString, SWIG_Callback1_t callbackGetFileTypeCount, SWIG_Callback2_t callbackGetFileType, SWIG_Callback3_t callbackGetFileExtention, SWIG_Callback4_t callbackReadFile__SWIG_0, SWIG_Callback5_t callbackReadFile__SWIG_1);

private:
    SWIG_Callback0_t swig_callbackGetAboutString;
    SWIG_Callback1_t swig_callbackGetFileTypeCount;
    SWIG_Callback2_t swig_callbackGetFileType;
    SWIG_Callback3_t swig_callbackGetFileExtention;
    SWIG_Callback4_t swig_callbackReadFile__SWIG_0;
    SWIG_Callback5_t swig_callbackReadFile__SWIG_1;
    void swig_init_callbacks();
};


#endif
