/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_eh_WRAP_H_
#define SWIG_eh_WRAP_H_

struct SwigDirector_Callback : public eh::Callback, public Swig::Director {

public:
    SwigDirector_Callback();
    virtual ~SwigDirector_Callback();
    virtual void call(float value);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(float);
    void swig_connect_director(SWIG_Callback0_t callbackcall);

private:
    SWIG_Callback0_t swig_callbackcall;
    void swig_init_callbacks();
};


#endif
