//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eh {

public class Vec3Vector : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<Vec3>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vec3Vector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vec3Vector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vec3Vector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ehPINVOKE.delete_Vec3Vector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Vec3Vector(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Vec3 element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Vec3 this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Vec3[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Vec3[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Vec3[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<Vec3> global::System.Collections.Generic.IEnumerable<Vec3>.GetEnumerator() {
    return new Vec3VectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new Vec3VectorEnumerator(this);
  }

  public Vec3VectorEnumerator GetEnumerator() {
    return new Vec3VectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class Vec3VectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Vec3>
  {
    private Vec3Vector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public Vec3VectorEnumerator(Vec3Vector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Vec3 Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Vec3)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    ehPINVOKE.Vec3Vector_Clear(swigCPtr);
  }

  public void Add(Vec3 x) {
    ehPINVOKE.Vec3Vector_Add(swigCPtr, Vec3.getCPtr(x));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = ehPINVOKE.Vec3Vector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = ehPINVOKE.Vec3Vector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    ehPINVOKE.Vec3Vector_reserve(swigCPtr, n);
  }

  public Vec3Vector() : this(ehPINVOKE.new_Vec3Vector__SWIG_0(), true) {
  }

  public Vec3Vector(Vec3Vector other) : this(ehPINVOKE.new_Vec3Vector__SWIG_1(Vec3Vector.getCPtr(other)), true) {
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec3Vector(int capacity) : this(ehPINVOKE.new_Vec3Vector__SWIG_2(capacity), true) {
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  private Vec3 getitemcopy(int index) {
    Vec3 ret = new Vec3(ehPINVOKE.Vec3Vector_getitemcopy(swigCPtr, index), true);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Vec3 getitem(int index) {
    Vec3 ret = new Vec3(ehPINVOKE.Vec3Vector_getitem(swigCPtr, index), false);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Vec3 val) {
    ehPINVOKE.Vec3Vector_setitem(swigCPtr, index, Vec3.getCPtr(val));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(Vec3Vector values) {
    ehPINVOKE.Vec3Vector_AddRange(swigCPtr, Vec3Vector.getCPtr(values));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec3Vector GetRange(int index, int count) {
    global::System.IntPtr cPtr = ehPINVOKE.Vec3Vector_GetRange(swigCPtr, index, count);
    Vec3Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vec3Vector(cPtr, true);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Vec3 x) {
    ehPINVOKE.Vec3Vector_Insert(swigCPtr, index, Vec3.getCPtr(x));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, Vec3Vector values) {
    ehPINVOKE.Vec3Vector_InsertRange(swigCPtr, index, Vec3Vector.getCPtr(values));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    ehPINVOKE.Vec3Vector_RemoveAt(swigCPtr, index);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    ehPINVOKE.Vec3Vector_RemoveRange(swigCPtr, index, count);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Vec3Vector Repeat(Vec3 value, int count) {
    global::System.IntPtr cPtr = ehPINVOKE.Vec3Vector_Repeat(Vec3.getCPtr(value), count);
    Vec3Vector ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vec3Vector(cPtr, true);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    ehPINVOKE.Vec3Vector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    ehPINVOKE.Vec3Vector_Reverse__SWIG_1(swigCPtr, index, count);
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, Vec3Vector values) {
    ehPINVOKE.Vec3Vector_SetRange(swigCPtr, index, Vec3Vector.getCPtr(values));
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
