//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace eh {

public class Vec4 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vec4(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vec4 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vec4() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ehPINVOKE.delete_Vec4(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public float x {
    set {
      ehPINVOKE.Vec4_x_set(swigCPtr, value);
    } 
    get {
      float ret = ehPINVOKE.Vec4_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      ehPINVOKE.Vec4_y_set(swigCPtr, value);
    } 
    get {
      float ret = ehPINVOKE.Vec4_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      ehPINVOKE.Vec4_z_set(swigCPtr, value);
    } 
    get {
      float ret = ehPINVOKE.Vec4_z_get(swigCPtr);
      return ret;
    } 
  }

  public float w {
    set {
      ehPINVOKE.Vec4_w_set(swigCPtr, value);
    } 
    get {
      float ret = ehPINVOKE.Vec4_w_get(swigCPtr);
      return ret;
    } 
  }

  public Vec4(float x, float y, float z, float w) : this(ehPINVOKE.new_Vec4__SWIG_0(x, y, z, w), true) {
  }

  public Vec4(Vec3 v, float w) : this(ehPINVOKE.new_Vec4__SWIG_1(Vec3.getCPtr(v), w), true) {
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec4(Vec4 v) : this(ehPINVOKE.new_Vec4__SWIG_2(Vec4.getCPtr(v)), true) {
    if (ehPINVOKE.SWIGPendingException.Pending) throw ehPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
