name: build
on: [push, pull_request]
jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: apt-get install
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils mesa-common-dev libsdl2-dev libglfw3-dev
          sudo apt-get install -y libgtk-3-dev libcairo2-dev libpango1.0-dev
      - name: build
        run: |
          sh build.sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
      - name: upload-artefacts
        uses: actions/upload-artifact@v2
        with:
          name: uwedit-linux
          path: ./bin/
  build-windows:
    name: build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: apt-get install
        run: |
          sudo apt-get update
          sudo apt-get install mingw-w64
      - name: build
        run: |
          export GOOS=windows GOACH=amd64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ CGO_ENABLED=1
          sh build.sh
      - name: upload-artefacts
        uses: actions/upload-artifact@v2
        with:
          name: uwedit-win
          path: ./bin/
